services:
  db:
    image: postgres:15
    container_name: go-graphql-blog-db
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: db
      POSTGRES_PASSWORD: db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always   

  blog:
    build: .
    ports:
      - "8080:8080"
    command: ["./main", "--config=./config/local.yaml", "--storage=postgres"]

volumes:
  postgres_data:
